#!/bin/bash

# create roundcube database / user
mysql <<EOF
CREATE USER '${ROUNDCUBEMAIL_DATABASE_USER}'@'${ROUNDCUBEMAIL_DATABASE_HOST}' IDENTIFIED BY '${ROUNDCUBEMAIL_DATABASE_PASSWORD}';
CREATE DATABASE ${ROUNDCUBEMAIL_DATABASE} /*!40101 CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
GRANT ALL PRIVILEGES ON ${ROUNDCUBEMAIL_DATABASE}.* TO '${ROUNDCUBEMAIL_DATABASE_USER}'@'${ROUNDCUBEMAIL_DATABASE_HOST}' WITH GRANT OPTION;
FLUSH PRIVILEGES;
exit
EOF

# create vimbadmin database / user
mysql <<EOF
CREATE USER '${VIMBADMIN_DATABASE_USER}'@'${VIMBADMIN_DATABASE_HOST}' IDENTIFIED BY '${VIMBADMIN_DATABASE_PASSWORD}';
CREATE DATABASE '${VIMBADMIN_DATABASE}' /*!40101 CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
GRANT ALL PRIVILEGES ON ${VIMBADMIN_DATABASE}.* TO '${VIMBADMIN_DATABASE_USER}'@'${VIMBADMIN_DATABASE_HOST}' WITH GRANT OPTION;
FLUSH PRIVILEGES;
exit
EOF
